apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mydemoapp
  namespace: argocd
  annotations: 
    argocd-image-updater.argoproj.io/image-list: quay.io/miniprojects/saysmooth:~v0.2
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/argo-secret
    argocd-image-updater.argoproj.io/git-branch: main
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: ssh://git@github.com/ruthvik2424/demorepo.git
    targetRevision: main
    path: dev
  destination: 
    server: https://kubernetes.default.svc
    namespace: mydemoapp
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
