apiversion: apps/v1
kind: Deployment
metadata:
  name: mydemoapp
 spec:
  selector:
    matchLabels:
      app: mydemoapp
    replicas: 2
    template:
      metadata:
        labels:
          app: mydemoapp
      spec:
        containers:
        - name: mydemoapp
          image: docker.io/ruthvik2424/demoproject:1.3.0
          ports:
          - containerPort: 9000
      
