apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-ingress
spec:
  rules:
    - host: api.192.168.49.2
      http:
        paths:
          - pathType: Prefix
            path: "/*"
            backend:
              service:
                name: myapi-service
                port:
                  number: 5000
