apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-ingress
spec:
  rules:
    - host: "api.com"
      http:
        paths:
          - pathType: Prefix
            path: "/process"
            backend:
              service:
                serviceName: myapi-service
                servicePort: 5000
