apiVersion: v1
kind: Service
metadata:
  name: mydemo-service
spec:
  selector:
    app: mydemoapp
  type: LoadBalancer
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
    nodePort: 31000
