name: Building image

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  build-image:
    runs-on: ubuntu-latest
    
    steps: 
    - name: Running
      run: ls -l 
    - name: Build and Push Docker Image
      uses: mr-smithers-excellent/docker-build-push@v4
      with:
        image: ruthvik2424/demoproject
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
